const tiles = [
  {
    name: 'house',
    emoji: '🏠',
    category: 'Residential',
    density: 0.25,
    price: 10,
    revenue: 10,
    maintenance: 2,
    pollution: 0.1,
    crime: 0.1,
    moves: false,
    description: 'A single-family home.'
  },
  {
    name: 'house with garden',
    emoji: '🏡',
    category: 'Residential',
    density: 0.25,
    price: 15,
    revenue: 12,
    maintenance: 3,
    pollution: 0.1,
    crime: 0.1,
    moves: false,
    description: 'A house with a garden.'
  },
  {
    name: 'apartment building',
    emoji: '🏢',
    category: 'Residential',
    density: 0.5,
    price: 30,
    revenue: 20,
    maintenance: 4,
    pollution: 0.3,
    crime: 0.2,
    moves: false,
    description: 'A building with multiple apartments.'
  },
  {
    name: 'skyscraper',
    emoji: '🏙️',
    category: 'Residential',
    density: 1,
    price: 50,
    revenue: 30,
    maintenance: 6,
    pollution: 0.5,
    crime: 0.3,
    moves: false,
    description: 'A tall building with multiple floors used for residential purposes.'
  },
  {
    name: 'convenience store',
    emoji: '🏪',
    category: 'Commercial',
    density: 0.25,
    price: 20,
    revenue: 15,
    maintenance: 3,
    pollution: 0.2,
    crime: 0.1,
    moves: false,
    description: 'A small store that sells everyday items.'
  },
  {
    name: 'fast food restaurant',
    emoji: '🍔',
    category: 'Commercial',
    density: 0.25,
    price: 25,
    revenue: 18,
    maintenance: 4,
    pollution: 0.3,
    crime: 0.2,
    moves: false,
    description: 'A restaurant that serves fast food.'
  },
  {
    name: 'shop',
    emoji: '🏬',
    category: 'Commercial',
    density: 0.25,
    price: 30,
    revenue: 20,
    maintenance: 4,
    pollution: 0.2,
    crime: 0.1,
    moves: false,
    description: 'A large store that sells a variety of goods.'
  },
  {
    name: 'small office',
    emoji: '🏢',
    category: 'Commercial',
    density: 0.5,
    price: 35,
    revenue: 25,
    maintenance: 5,
    pollution: 0.3,
    crime: 0.2,
    moves: false,
    description: 'A small office building.'
  },
  {
    name: 'hotel',
    emoji: '🏨',
    category: 'Commercial',
    density: 1,
    price: 60,
    revenue: 40,
    maintenance: 8,
    pollution: 0.4,
    crime: 0.3,
    moves: false,
    description: 'A building with rooms for travelers to stay in.'
  },
  {
    name: 'bank',
    emoji: '🏦',
    category: 'Commercial',
    density: 1,
    price: 70,
    revenue: 50,
    maintenance: 10,
    pollution: 0.5,
    crime: 0.4,
    moves: false,
    description: 'A financial institution that accepts deposits from the public.'
  },
  {
    name: 'large office building',
    emoji: '🏢',
    category: 'Commercial',
    density: 1,
    price: 80,
    revenue: 60,
    maintenance: 12,
    pollution: 0.6,
    crime: 0.4,
    moves: false,
    description: 'A large building with many offices.'
  },
  {
    name: 'shopping mall',
    emoji: '🏬',
    category: 'Commercial',
    density: 1,
    price: 100,
    revenue: 80,
    maintenance: 16,
    pollution: 0.8,
    crime: 0.6,
    moves: false,
    description: 'A large building with many stores.'
  },
  {
    name: 'mansion',
    emoji: '🏡',
    category: 'Residential',
    density: 0.25,
    price: 40,
    revenue: 30,
    maintenance: 6,
    pollution: 0.3,
    crime: 0.2,
    moves: false,
    description: 'A large and impressive house.'
  },
  {
    name: 'workshop',
    emoji: '🔧',
    category: 'Industrial',
    density: 0.25,
    price: 15,
    revenue: 10,
    maintenance: 2,
    pollution: 0.1,
    crime: 0.1,
    moves: false,
    description: 'A place where tools and equipment are used to create or repair things.'
  },
  {
    name: 'small factory',
    emoji: '🏭',
    category: 'Industrial',
    density: 0.5,
    price: 30,
    revenue: 20,
    maintenance: 4,
    pollution: 0.3,
    crime: 0.2,
    moves: false,
    description: 'A small factory that produces goods.'
  },
  {
    name: 'warehouse',
    emoji: '🏚️',
    category: 'Industrial',
    density: 0.5,
    price: 25,
    revenue: 15,
    maintenance: 3,
    pollution: 0.2,
    crime: 0.1,
    moves: false,
    description: 'A large building used for storage of goods.'
  },
  {
    name: 'manufacturing plant',
    emoji: '🏭',
    category: 'Industrial',
    density: 1,
    price: 50,
    revenue: 40,
    maintenance: 8,
    pollution: 0.6,
    crime: 0.4,
    moves: false,
    description: 'A large factory that produces goods on a large scale.'
  },
  {
    name: 'power plant',
    emoji: '💡',
    category: 'Industrial',
    density: 1,
    price: 70,
    revenue: 50,
    maintenance: 10,
    pollution: 0.8,
    crime: 0.5,
    moves: false,
    description: 'A plant that generates electricity.'
  },
  {
    name: 'chemical plant',
    emoji: '⚗️',
    category: 'Industrial',
    density: 1,
    price: 80,
    revenue: 60,
    maintenance: 12,
    pollution: 1,
    crime: 0.7,
    moves: false,
    description: 'A plant where chemicals are produced.'
  },
  {
    name: 'oil refinery',
    emoji: '🛢️',
    category: 'Industrial',
    density: 1,
    price: 90,
    revenue: 70,
    maintenance: 14,
    pollution: 0.9,
    crime: 0.6,
    moves: false,
    description: 'A plant that processes crude oil into usable products.'
  },
  {
    name: 'road',
    emoji: '🛣️',
    category: 'Transportation',
    density: 0.25,
    price: 5,
    revenue: 0,
    maintenance: 1,
    pollution: 0.1,
    crime: 0.05,
    moves: false,
    description: 'A street.'
  }
]

const transportation = [
  {
    name: 'car',
    emoji: '🚗',
    category: 'Transportation',
    density: 0.5,
    price: 10,
    revenue: 0,
    maintenance: 1,
    pollution: 0.05,
    crime: 0.05,
    moves: true,
    description: 'A small motorized vehicle with four wheels, designed to carry a small number of passengers.'
  },
  {
    name: 'bus',
    emoji: '🚌',
    category: 'Transportation',
    density: 1,
    price: 20,
    revenue: 0,
    maintenance: 2,
    pollution: 0.1,
    crime: 0.1,
    moves: true,
    description: 'A large motorized vehicle designed to carry passengers, typically along a fixed route.'
  },
  {
    name: 'taxi',
    emoji: '🚕',
    category: 'Transportation',
    density: 0.5,
    price: 15,
    revenue: 0,
    maintenance: 1,
    pollution: 0.05,
    crime: 0.05,
    moves: true,
    description: 'A car that is used for hire to carry passengers, often with a taximeter.'
  },
  {
    name: 'delivery truck',
    emoji: '🚚',
    category: 'Transportation',
    density: 0.5,
    price: 20,
    revenue: 0,
    maintenance: 2,
    pollution: 0.2,
    crime: 0.1,
    moves: true,
    description: 'A large vehicle used for transporting goods.'
  },
  {
    name: 'police car',
    emoji: '🚓',
    category: 'Transportation',
    density: 0.5,
    price: 25,
    revenue: 0,
    maintenance: 2,
    pollution: 0.1,
    crime: 0.05,
    moves: true,
    description: 'A car used by law enforcement officers to patrol the streets and respond to emergencies.'
  },
  {
    name: 'ambulance',
    emoji: '🚑',
    category: 'Transportation',
    density: 0.5,
    price: 30,
    revenue: 0,
    maintenance: 3,
    pollution: 0.1,
    crime: 0.05,
    moves: true,
    description: 'A vehicle used to transport sick or injured people to medical facilities.'
  },
  {
    name: 'fire engine',
    emoji: '🚒',
    category: 'Transportation',
    density: 0.5,
    price: 35,
    revenue: 0,
    maintenance: 3,
    pollution: 0.1,
    crime: 0.05,
    moves: true,
    description: 'A vehicle used by firefighters to respond to fires and other emergencies.'
  },
  {
    name: 'bicycle',
    emoji: '🚲',
    category: 'Transportation',
    density: 0.25,
    price: 5,
    revenue: 0,
    maintenance: 0,
    pollution: 0,
    crime: 0,
    moves: true,
    description: 'A vehicle with two wheels that is propelled by pedals.'
  },
  {
    name: 'train',
    emoji: '🚆',
    category: 'Transportation',
    density: 1,
    price: 50,
    revenue: 0,
    maintenance: 4,
    pollution: 0.2,
    crime: 0.1,
    moves: true,
    description:
      'A long, connected series of railway cars or wagons, typically powered by a locomotive, that transport passengers or goods on a railway track.'
  },
  {
    name: 'light rail',
    emoji: '🚈',
    category: 'Transportation',
    density: 1,
    price: 40,
    revenue: 0,
    maintenance: 3,
    pollution: 0.1,
    crime: 0.1,
    moves: true,
    description:
      'A form of urban rail transit that uses a mix of tram and metro features to provide efficient and frequent service in urban areas.'
  },
  {
    name: 'metro',
    emoji: '🚇',
    category: 'Transportation',
    density: 1,
    price: 50,
    revenue: 0,
    maintenance: 4,
    pollution: 0.2,
    crime: 0.1,
    moves: true,
    description: 'An underground or elevated railway system in a city that is generally used for mass transit.'
  },
  {
    name: 'tram',
    emoji: '🚋',
    category: 'Transportation',
    density: 1,
    price: 35,
    revenue: 0,
    maintenance: 3,
    pollution: 0.1,
    crime: 0.1,
    moves: true,
    description:
      'A rail vehicle that runs on tracks along public urban streets, and often has right-of-way over motor traffic.'
  },
  {
    name: 'monorail',
    emoji: '🚝',
    category: 'Transportation',
    density: 1,
    price: 60,
    revenue: 0,
    maintenance: 5,
    pollution: 0.2,
    crime: 0.1,
    moves: true,
    description: 'A single rail serving as a track for passenger or freight vehicles.'
  },
  {
    name: 'airplane',
    emoji: '✈️',
    category: 'Transportation',
    density: 2,
    price: 100,
    revenue: 0,
    maintenance: 8,
    pollution: 0.4,
    crime: 0.2,
    moves: true,
    description:
      'A powered flying vehicle with fixed wings and a weight greater than that of the air it displaces, used for transportation of passengers and cargo.'
  },
  {
    name: 'helicopter',
    emoji: '🚁',
    category: 'Transportation',
    density: 0.5,
    price: 70,
    revenue: 0,
    maintenance: 5,
    pollution: 0.2,
    crime: 0.1,
    moves: true,
    description: 'A type of rotorcraft in which lift and thrust are supplied by rotors.'
  }
]

export { tiles, transportation }
